name: Packer Template Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check-packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Zip webapp file
        run: cd ../ && zip -r webapp.zip webapp && cd - && cp ../webapp.zip .
  
      - name: Packer Init
        run: packer init ./packer
  
      - name: Packer Format
        run: packer fmt -check ./packer
  
      - name: Packer Validate
        run: packer validate ./packer
