name: Packer Template Checks

on:
  pull_request:
    branches:
      - main

jobs:
  check-packer:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Packer
      - name: Install Packer
        run: |
          sudo apt-get update
          sudo apt-get install -y packer

      # Step 3: Run packer fmt
      # If packer fmt modifies any files, the workflow will fail
      - name: Run packer fmt
        id: packer_fmt
        run: |
          packer fmt -check -diff .

      # Step 4: Run packer validate
      # If packer validate fails, the workflow will fail
      - name: Run packer validate
        run: |
          packer validate .
