name: PR Status Checks

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    env:
      # Environment variables sourced from GitHub Secrets
      PORT: ${{ secrets.PORT }}
      BCRYPT_SALT_ROUNDS: ${{ secrets.BCRYPT_SALT_ROUNDS }}

    steps:
      # Step 1: Print environment variables for debugging (optional)
      - name: Print Environment Variables for Debugging
        run: |
          echo "-----------------------------"
          echo "Environment Variables:"
          echo "PORT: $PORT"
          echo "BCRYPT_SALT_ROUNDS: $BCRYPT_SALT_ROUNDS"
          echo "-----------------------------"

      # Step 2: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Step 4: Cache Node.js dependencies to speed up workflow
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 5: Install project dependencies
      - name: Install Dependencies
        run: npm install

      # Step 6: Run tests (integration and unit tests)
      - name: Run Integration Tests
        run: npm run test
