name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: cloudDB
          POSTGRES_USER: cloudUser
          POSTGRES_PASSWORD: Cloud@12345
        options: >
          --health-cmd="pg_isready" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the environment (in this case, Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL
        run: |
          until docker exec ${{ job.services.db.id }} pg_isready -h 127.0.0.1 -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      # Create the .env file with environment variables
      - name: Create .env file
        run: |
          echo "PORT=3000" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=cloudUser" >> .env
          echo "DB_PASSWORD=Cloud@12345" >> .env
          echo "DB_DATABASE=cloudDB" >> .env
          echo "DB_POOL_MAX=5" >> .env
          echo "DB_POOL_MIN=0" >> .env
          echo "DB_POOL_ACQUIRE=30000" >> .env
          echo "DB_POOL_IDLE=10000" >> .env
          echo "BCRYPT_SALT_ROUNDS=10" >> .env

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test
